name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repository
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Sync with upstream
        id: sync_step
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'frankiejun/serv00-play'
          source_branch: 'main'
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for errors
        if: failure()
        run: echo "Sync failed! Please check the logs for more details."

      - name: Sync success message
        if: success()
        run: echo "Sync completed successfully!"
